name: AppleScript Decompile

on: [push]

jobs:
  decompile:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Decompile with osacompile
        run: |
          osacompile -d 1.scpt
