name: AppleScript Decompile

on: [push]

jobs:
  decompile:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Fix file type
        run: |
          SetFile -t osas 1.scpt

      - name: Decompile scpt
        run: |
          osadecompile 1.scpt
